"""empty message

Revision ID: 095b296ac8d5
Revises: 
Create Date: 2022-07-06 17:14:11.438514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095b296ac8d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('room')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('cash', sa.TEXT(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('sun', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['name_card.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash'),
    sa.UniqueConstraint('comment'),
    sa.UniqueConstraint('sun'),
    sa.UniqueConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('name_card')
    # ### end Alembic commands ###
