"""empty message

Revision ID: ce876eea87e8
Revises: 
Create Date: 2022-07-11 20:21:03.084668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce876eea87e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('surname', sa.String(length=32), server_default='Default', nullable=False),
    sa.Column('room', sa.String(), server_default='Default', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('cash', sa.TEXT(), nullable=True),
    sa.Column('sun', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), server_default='Default', nullable=False),
    sa.Column('comment', sa.Text(), server_default='Default', nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['name_card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('name_card')
    # ### end Alembic commands ###
