"""add surname

Revision ID: ed9f3e483440
Revises: eef245cb415c
Create Date: 2022-07-07 10:18:35.036398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9f3e483440'
down_revision = 'eef245cb415c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('name_card', sa.Column('surname', sa.String(length=32), server_default='Default', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('name_card', 'surname')
    # ### end Alembic commands ###
